### ISSUE TITLE
Paladin error - does not run anywhere with his feet

### ISSUE THREAD

**Issue by Andrey5Ka** [aeon0/botty#305]
Version 5 and 5.1

1.When entering any locations (without enigma and tp):
We teleport to Travinkal and this error appears:
HAMMERDIN
[2021-12-19 00:55:02,336] DEBUG      Traverse from a3_trav_start to a3_trav_center_stairs
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "bot.py", line 125, in start
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 322, in on_run_trav
  File "run\trav.py", line 49, in battle
  File "pather.py", line 372, in traverse_nodes
  File "char\i_char.py", line 102, in move
  File "keyboard\__init__.py", line 379, in send
  File "keyboard\__init__.py", line 358, in parse_hotkey
  File "keyboard\__init__.py", line 358, in <genexpr>
  File "keyboard\__init__.py", line 309, in key_to_scan_codes
  File "keyboard\_canonical_names.py", line 1239, in normalize_name
ValueError: Can only normalize non-empty string names. Unexpected ''

2.We teleport to any location on act 5 and this error appears
[2021-12-18 01:02:03,630] DEBUG      Traverse from a5_town_start to a5_malah
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "bot.py", line 125, in start
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 209, in on_maintenance
  File "town\town_manager.py", line 81, in heal
  File "town\a5.py", line 29, in heal
  File "pather.py", line 372, in traverse_nodes
  File "char\i_char.py", line 102, in move
  File "keyboard\__init__.py", line 379, in send
  File "keyboard\__init__.py", line 358, in parse_hotkey
  File "keyboard\__init__.py", line 358, in <genexpr>
  File "keyboard\__init__.py", line 309, in key_to_scan_codes
  File "keyboard\_canonical_names.py", line 1239, in normalize_name
ValueError: Can only normalize non-empty string names. Unexpected ''
That is, hammerdin does not run anywhere with his feet !!!

**Comment by Andrey5Ka** [comment]
I would be grateful if you could tell me where to look in the program code

**Comment by aeon0** [comment]
it quite specifically tells you where to look in the code: L102 in i_char.py

https://github.com/aeon0/botty/blob/1f482d5dcefc121692dd8a1add7070b57432423a/src/char/i_char.py#L102

You don't have your force_move hotkey set.

**Comment by Andrey5Ka** [comment]
What is "force_move"? I didn't install it because it's not in the game, I poke with the mouse.
https://github.com/aeon0/botty/blob/1f482d5dcefc121692dd8a1add7070b57432423a/src/char/i_char.py#L102              
 if force_move:
                keyboard.send(self._config.char["force_move"])
            else:
                mouse.click(button="left")

Where is the left mouse click?

> в нем совершенно конкретно указано, где искать код: L102 в i_char.py
> 
> https://github.com/aeon0/botty/blob/1f482d5dcefc121692dd8a1add7070b57432423a/src/char/i_char.py#L102
> 
> У вас нет набора горячих клавиш force_move.
