### ISSUE TITLE
Bug: Start a new game with little health

### ISSUE THREAD

**Issue by Andrey5Ka** [aeon0/botty#309]
v. 5.1
Start a new game with a small amount of health. Drinks a can of "health" and turns off. . The code appears (see below):

[2021-12-20 00:57:04,228] DEBUG      Waiting for Template ['A5_TOWN_0', 'A5_TOWN_1', 'A4_TOWN_4', 'A4_TOWN_5', 'A3_TOWN_0', 'A3_TOWN_1']
[2021-12-20 00:57:12,138] DEBUG      Drink health potion in slot 1. HP: 44.7%, Mana: 99.2%
[2021-12-20 00:57:13,003] DEBUG      Found Match: A5_TOWN_1 (87.2% confidence)
[2021-12-20 00:57:13,064] INFO       Health Manager is now pausing
[2021-12-20 00:57:13,784] DEBUG      Will pickup: {'rejuv': 0, 'health': 3, 'mana': 0}
[2021-12-20 00:57:13,808] INFO       Healing at next possible Vendor
[2021-12-20 00:57:13,809] DEBUG      Traverse from a5_town_start to a5_malah
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "bot.py", line 125, in start
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 209, in on_maintenance
  File "town\town_manager.py", line 81, in heal
  File "town\a5.py", line 29, in heal
  File "pather.py", line 372, in traverse_nodes
  File "char\i_char.py", line 102, in move
  File "keyboard\__init__.py", line 379, in send
  File "keyboard\__init__.py", line 358, in parse_hotkey
  File "keyboard\__init__.py", line 358, in <genexpr>
  File "keyboard\__init__.py", line 309, in key_to_scan_codes
  File "keyboard\_canonical_names.py", line 1239, in normalize_name
ValueError: Can only normalize non-empty string names. Unexpected ''

**Comment by nekolr** [comment]
> 

same as #308, please set `force_move` key
