### ISSUE TITLE
Botty will stop if not possible to connect to discord hook

### ISSUE THREAD

**Issue by jagarop** [aeon0/botty#478]
**Botty Version**
Botty 0.6.4

**Describe the bug**
Botty will stop if not possible to connect to discord hook

**Expected behavior**
Give an warning instead of unhandled exception

**Screenshots / Video**
https://i.imgur.com/agWM9Wz.png

**Logs**
Exception in thread Thread-6:
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 73, in create_connection
  File "socket.py", line 954, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 358, in connect
  File "urllib3\connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000000008409D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 440, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='discord.com', port=443): Max retries exceeded with url: /api/webhooks/932417662947065897/M8r8JyqtTOZHB7cdymIsAYQO6dTxaiWlPA6svjDoUxzBEY3ikdLh9MTX84VCKHIuT67g (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000000008409D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "bot.py", line 158, in start
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 199, in on_create_game
  File "game_stats.py", line 79, in log_start_game
  File "game_stats.py", line 159, in _send_status_update
  File "messenger.py", line 34, in send_message
  File "api\generic_api.py", line 31, in send_message
  File "api\generic_api.py", line 61, in _send
  File "requests\api.py", line 117, in post
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='discord.com', port=443): Max retries exceeded with url: /api/webhooks/932417662947065897/M8r8JyqtTOZHB7cdymIsAYQO6dTxaiWlPA6svjDoUxzBEY3ikdLh9MTX84VCKHIuT67g (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000000008409D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by mgleed** [comment]
Resolved on a recent pr
