### ISSUE TITLE
Diablo Path broken saying clear trash not implemented even without clear trash

### ISSUE THREAD

**Issue by NeoIsrafil** [aeon0/botty#605]
**Is it really a Bug report?**

I believe so, yes, alternatively, if it isnt completed yet, it may be useful to add a comment line in the params file that says what paths are and are not implemented, or at least to add to the sorc a "supported paths" list like the others have.

**Botty Version**

 Using Precompiled 6.7 release.

**Describe the bug**
Botty fails to run the Diablo route with or without CS_trash on with a cs_Trash not implemented error. Unsure if Diablo route is simply not implemented.  This is an interesting project... Might be fun to learn the syntax and how to compile from master so I can get this working but would probably need help getting to that point of a first compiled file.  I'm better at editing code and finding logic errors than writing it.

Using the precompiled release and as default settings as possible, even cleared, redownloaded, and re-created it from scratch, same error.

**To Reproduce**
 Run botty set to diablo only, lightning sorc (pretty basic setup with a frost orb incase it needed it) with or without cs trash
Botty fails with a CS trash not implemented error at the beginning of chaos sanctuary if set to 1, or 2 teleports after the calibration portal is set at the pentagram if 0

**Expected behavior**
Botty would run diablo seals and either clear, or not clear trash, seems to be something failing.  

**Screenshots / Video**
If applicable, add screenshots or even better a short video of the error happening to help explain your problem. Botty often automatically makes screenshots when something goes wrong. Add these also.

**Logs**
Add the relevant part of the info.log in this section. Either upload it as a fail or copy-paste the relevant part in here.
[2022-02-27 00:34:35,956] DEBUG      Using WinAPI to search for window under D2R.exe process
[2022-02-27 00:34:35,958] DEBUG      Set offsets: left 228px, top 152px
[2022-02-27 00:34:39,481] INFO       Start health monitoring
[2022-02-27 00:34:39,482] INFO       Start Death monitoring
[2022-02-27 00:34:40,092] INFO       Setting up Light Sorc
[2022-02-27 00:34:40,097] INFO       Doing runs: odict_keys(['run_diablo'])
[2022-02-27 00:34:40,098] INFO       Starting game #1
[2022-02-27 00:34:40,098] DEBUG      Waiting for templates: ['MAIN_MENU_TOP_LEFT', 'MAIN_MENU_TOP_LEFT_DARK', 'A5_TOWN_0', 'A5_TOWN_1', 'A4_TOWN_4', 'A4_TOWN_5', 'A3_TOWN_0', 'A3_TOWN_1', 'A2_TOWN_0', 'A2_TOWN_1', 'A2_TOWN_10', 'A1_TOWN_1', 'A1_TOWN_3']
[2022-02-27 00:34:59,008] DEBUG      Found Match: A5_TOWN_1 (80.9% confidence)
[2022-02-27 00:34:59,008] DEBUG      Waiting for templates: ['A5_TOWN_0', 'A5_TOWN_1', 'A4_TOWN_4', 'A4_TOWN_5', 'A3_TOWN_0', 'A3_TOWN_1', 'A2_TOWN_0', 'A2_TOWN_1', 'A2_TOWN_10', 'A1_TOWN_1', 'A1_TOWN_3']
[2022-02-27 00:34:59,574] DEBUG      Found Match: A5_TOWN_1 (80.5% confidence)
[2022-02-27 00:35:01,775] DEBUG      Waiting for templates: ['ITEM_PICKUP_ENABLED', 'ITEM_PICKUP_DISABLED']
[2022-02-27 00:35:01,786] DEBUG      Found Match: ITEM_PICKUP_ENABLED (93.8% confidence)
[2022-02-27 00:35:02,286] INFO       Activated /nopickup
[2022-02-27 00:35:02,337] INFO       Capabilities: CharacterCapabilities(can_teleport_natively=True, can_teleport_with_charges=False)
[2022-02-27 00:35:03,076] DEBUG      Will pickup: {'rejuv': 4, 'health': 0, 'mana': 0}
[2022-02-27 00:35:04,842] INFO       Run Diablo
[2022-02-27 00:35:04,842] DEBUG      settings for trash =True
[2022-02-27 00:35:04,843] DEBUG      Traverse from a5_town_start to a5_wp
[2022-02-27 00:35:10,776] INFO       Health Manager is now active
[2022-02-27 00:35:11,489] DEBUG      Traverse: [600]
[2022-02-27 00:35:12,481] DEBUG      ROF: Calibrated at WAYPOINT
[2022-02-27 00:35:17,648] DEBUG      Kill trash at location: rof_01
Exception in thread Thread-6:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "bot.py", line 167, in start
  File "bot.py", line 187, in trigger_or_stop
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 464, in on_run_diablo
  File "run\diablo.py", line 472, in battle
  File "run\diablo.py", line 249, in _river_of_flames_trash
  File "char\i_char.py", line 328, in kill_cs_trash
ValueError: Diablo CS Trash is not implemented!
[2022-02-27 00:35:29,168] DEBUG      Drink mana potion in slot 2. HP: 97.9%, Mana: 49.5%

**Additional info**
Add any other information about the problem here.

**Comment by xMrMurderx** [comment]
Asked about this in discord. Apparently it is only implemented for paladins, no sorc yet.

**Comment by mgleed** [comment]
Yeah not currently implemented on classes other than hammerdin.
