### ISSUE TITLE
several issues, problems with button presses, ...

### ISSUE THREAD

**Issue by sukram91** [aeon0/botty#636]
Issue 1:
precompiled v0.7.1 and precompiled v0.6.7 (low end pc)

bot get stuck in movement path, waits for hotkey teleport, mouse tries to move -> after pressing teleport hotkey manually bot continues 
hammerdin all hotkeys set (vigor, redemption, ...)

#########################################################

Issue 2: 
precompiled v0.7.1 (low end pc)

ESC loop after inventory, stash, cain

#########################################################

Issue 3:
precompiled v0.7.1 (low end pc)

bot tries exiting the game but get stuck because he exiting the ESC screen 
similar issue as above #2

#########################################################

Issue 4:
precompiled v0.7.1 and precompiled v0.6.7 (low end pc)

occured after several runs, bot used teleport before
happened before diablo or nihlathak runs

Exception in thread Thread-8:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "bot.py", line 154, in start
  File "bot.py", line 174, in trigger_or_stop
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 468, in on_run_nihlathak
  File "run\nihlathak.py", line 32, in approach
ValueError: Nihlathak requires teleport

#########################################################

(Issue 5: seems to be fixed in v0.7.1)
precompiled v0.6.7 (low end pc)

hotkeys set to a 0-9 key didnt work -> keyboard.send doesnt allow type integer

**Comment by ceya74** [comment]
well, when I start the bot, makes a game, types /nopickup, and stay there, it doesn't move at all. waited half an hour and nothing happened
