### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by jgj333boy** [aeon0/botty#645]
[0.7.1-dev 2022-03-18 00:48:12,093] DEBUG      Using WinAPI to search for window: WindowSpec(title_regex=None, process_name_regex='D2R\\.exe')
[0.7.1-dev 2022-03-18 00:48:12,102] DEBUG      Set offsets: left 320px, top 160px
Set D2R to be always on top
[0.7.1-dev 2022-03-18 00:48:12,173] INFO       Start health monitoring
[0.7.1-dev 2022-03-18 00:48:12,174] INFO       Start Death monitoring
[0.7.1-dev 2022-03-18 00:48:12,411] INFO       Setting up Blizz Sorc
[0.7.1-dev 2022-03-18 00:48:12,412] INFO       Doing runs: odict_keys(['run_diablo'])
[0.7.1-dev 2022-03-18 00:48:12,413] INFO       Starting game #1
[0.7.1-dev 2022-03-18 00:48:12,414] DEBUG      Waiting for templates: ['MAIN_MENU_TOP_LEFT', 'MAIN_MENU_TOP_LEFT_DARK', 'A5_TOWN_0', 'A5_TOWN_1', 'A4_TOWN_4', 'A4_TOWN_5', 'A3_TOWN_0', 'A3_TOWN_1', 'A2_TOWN_0', 'A2_TOWN_1', 'A2_TOWN_10', 'A1_TOWN_1', 'A1_TOWN_3']
[0.7.1-dev 2022-03-18 00:48:13,601] DEBUG      Found Match: A4_TOWN_5 (92.0% confidence)
[0.7.1-dev 2022-03-18 00:48:13,603] DEBUG      Waiting for templates: ['A5_TOWN_0', 'A5_TOWN_1', 'A4_TOWN_4', 'A4_TOWN_5', 'A3_TOWN_0', 'A3_TOWN_1', 'A2_TOWN_0', 'A2_TOWN_1', 'A2_TOWN_10', 'A1_TOWN_1', 'A1_TOWN_3']
[0.7.1-dev 2022-03-18 00:48:14,609] DEBUG      Found Match: A4_TOWN_5 (91.9% confidence)
[0.7.1-dev 2022-03-18 00:48:19,875] DEBUG      ['ITEM_PICKUP_ENABLED', 'ITEM_PICKUP_DISABLED'] not found 
after 3 seconds
[0.7.1-dev 2022-03-18 00:48:19,876] ERROR      Failed to detect if /nopickup command was applied or not
[0.7.1-dev 2022-03-18 00:48:20,165] INFO       Capabilities: CharacterCapabilities(can_teleport_natively=True, can_teleport_with_charges=False)
[0.7.1-dev 2022-03-18 00:48:21,935] DEBUG      BELT_EXPANDABLE still found after 1 seconds
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\jgj33\miniconda3\envs\botty\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\jgj33\miniconda3\envs\botty\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\botty-master\src\bot.py", line 154, in start
    self.trigger_or_stop('init')
  File "C:\botty-master\src\bot.py", line 174, in trigger_or_stop
    self.trigger(name, **kwargs)
  File "C:\Users\jgj33\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 899, in _get_trigger
    return event.trigger(model, *args, **kwargs)
  File "C:\Users\jgj33\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 401, in trigger    return self.machine._process(func)
  File "C:\Users\jgj33\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1201, in _process
    self._transition_queue[0]()
  File "C:\Users\jgj33\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 426, in _trigger
    return self._process(event_data)
  File "C:\Users\jgj33\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 435, in _process
    if trans.execute(event_data):
  File "C:\Users\jgj33\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 272, in execute    event_data.machine.callbacks(itertools.chain(event_data.machine.before_state_change, self.before), event_data)
  File "C:\Users\jgj33\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1123, in callbacks
    self.callback(func, event_data)
  File "C:\Users\jgj33\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1144, in callback
    func(*event_data.args, **event_data.kwargs)
  File "C:\botty-master\src\bot.py", line 275, in on_maintenance
    potion_type = _potion_type(_cut_potion_img(img, column, 0))
  File "C:\botty-master\src\inventory\belt.py", line 73, in _cut_potion_img
    return cut_roi(img, roi)
  File "C:\botty-master\src\utils\misc.py", line 94, in cut_roi
    return img[y:y+h, x:x+w]
TypeError: 'NoneType' object is not subscriptable

.
.
.........plz

**Comment by mgleed** [comment]
Fix your toggle belt hotkey. Make sure your keyboard is set to English.
