### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by xnsrt** [aeon0/botty#667]
Version: Precompiled v.0.7.2

when I start the bot, makes a game, types /nopickup, and messages was printed on the "Exception in thread Thread-7:" python console window, after that it doesn't move at all.

Which part should I check?
Thank you.

[0.7.2 2022-03-27 15:54:43,641] DEBUG      Using WinAPI to search for window: WindowSpec(title_regex=None, process_name_regex='D2R\\.exe')
[0.7.2 2022-03-27 15:54:43,659] DEBUG      Set offsets: left 641px, top 33px
Set D2R to be always on top
[0.7.2 2022-03-27 15:54:43,721] INFO       Start health monitoring
[0.7.2 2022-03-27 15:54:43,722] INFO       Start Death monitoring
[0.7.2 2022-03-27 15:54:43,862] INFO       Setting up Light Sorc
[0.7.2 2022-03-27 15:54:43,863] INFO       Doing runs: odict_keys(['run_pindle', 'run_shenk'])
[0.7.2 2022-03-27 15:54:43,864] INFO       Starting game #1
[0.7.2 2022-03-27 15:54:43,864] DEBUG      Waiting for templates: ['MAIN_MENU_TOP_LEFT', 'MAIN_MENU_TOP_LEFT_DARK', 'A5_TOWN_0', 'A5_TOWN_1', 'A4_TOWN_4', 'A4_TOWN_5', 'A3_TOWN_0', 'A3_TOWN_1', 'A2_TOWN_0', 'A2_TOWN_1', 'A2_TOWN_10', 'A1_TOWN_1', 'A1_TOWN_3']
[0.7.2 2022-03-27 15:54:44,810] DEBUG      Found Match: MAIN_MENU_TOP_LEFT (100.0% confidence)
[0.7.2 2022-03-27 15:54:44,824] DEBUG      Wait for Play button
[0.7.2 2022-03-27 15:54:44,838] DEBUG      Found Play Btn
[0.7.2 2022-03-27 15:54:46,177] DEBUG      Waiting for templates: ['A5_TOWN_0', 'A5_TOWN_1', 'A4_TOWN_4', 'A4_TOWN_5', 'A3_TOWN_0', 'A3_TOWN_1', 'A2_TOWN_0', 'A2_TOWN_1', 'A2_TOWN_10', 'A1_TOWN_1', 'A1_TOWN_3']
[0.7.2 2022-03-27 15:54:52,804] DEBUG      Found Match: A3_TOWN_1 (80.4% confidence)
[0.7.2 2022-03-27 15:54:55,615] INFO       Activated /nopickup
[0.7.2 2022-03-27 15:54:55,834] INFO       Capabilities: CharacterCapabilities(can_teleport_natively=True, can_teleport_with_charges=False)
[0.7.2 2022-03-27 15:54:56,875] DEBUG      BELT_EXPANDABLE still found after 1 seconds
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "bot.py", line 153, in start
  File "bot.py", line 173, in trigger_or_stop
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 274, in on_maintenance
  File "inventory\belt.py", line 105, in update_pot_needs
  File "inventory\belt.py", line 72, in _cut_potion_img
  File "utils\misc.py", line 94, in cut_roi
TypeError: 'NoneType' object is not subscriptable

**Comment by jagarop** [comment]
#664
