### ISSUE TITLE
Looks like the 7.2 build broke something, it's not playing nice with the core and the belt handling.  

### ISSUE THREAD

**Issue by NeoIsrafil** [aeon0/botty#678]
Belt_expandable still found after 1 seconds.
Tried completely unedited files from release, same exactl error.  I have noticed the old version started doing something weird too, its suddenly buying pots to fill up the inventory when there's already potions filling the belt.   Not sure if it just doesn't like something that was changed about the game itself recently or..I dunno.
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "bot.py", line 153, in start
  File "bot.py", line 173, in trigger_or_stop
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 274, in on_maintenance
  File "inventory\belt.py", line 105, in update_pot_needs
  File "inventory\belt.py", line 72, in _cut_potion_img
  File "utils\misc.py", line 94, in cut_roi
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "main.py", line 96, in <module>
  File "main.py", line 88, in main
  File "keyboard\__init__.py", line 886, in wait
KeyboardInterrupt
Press Enter to exit ...
Traceback (most recent call last):
  File "main.py", line 100, in <module>
EOFError
[17216] Failed to execute script 'main' due to unhandled exception!

Unsure if compile went poorly or if there's something interfering now..

**Comment by D2RLegit** [comment]
Fix your belt hotkey

**Comment by NeoIsrafil** [comment]
Yep, thanks.  Apparently this, and similar errors, are all showing up because SOMEONE decided to clear all the hotkeys for d2r... probably in one of the recent maints.  Couldn't figure out why a known good setup AND a new clean build both werent working suddenly.   Hopefully anyone who runs across this will learn from my stupid.
