### ISSUE TITLE
OCs exp error 

### ISSUE THREAD

**Issue by SpheresOfMadness** [aeon0/botty#704]
When starting a new game, botty mouses over the xp bar and I get a couple of errors saying that the integer is outside of range, If the bot continues (sometimes does not) at the end of the run it does the same thing, gets the same error message,  exits and gives me a thread_7 error and stops.

I can get it to stop giving me errors if I use imag debug mode and hover over the xp bar for a while, but must do it in every area that checks xp.

Though this has not been 100% successful

here is the message:

[7.2 2022-04-15 02:15:08,856] ERROR      EXP OCR Error: ['DIIIIIIIIIIIIID']
[7.2 2022-04-15 02:15:08,856] ERROR      EXP OCR Error: list index out of range
[7.2 2022-04-15 02:15:09,558] INFO       Health Manager is now pausing
[7.2 2022-04-15 02:15:09,559] INFO       End game. Elapsed time: 76.14s
[7.2 2022-04-15 02:15:09,560] DEBUG      Session length = 2 minutes, max_runtime_before_break_m 120.0.
Exception in thread Thread-23:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "bot.py", line 159, in start
  File "bot.py", line 179, in trigger_or_stop
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 205, in on_init
  File "game_stats.py", line 85, in log_start_game
  File "game_stats.py", line 213, in _save_stats_to_file
  File "game_stats.py", line 169, in _create_msg
ZeroDivisionError: float division by zero

**Comment by SpheresOfMadness** [comment]
This can be altogether avoided by setting condensed messages to 1 as a work around

**Comment by mgleed** [comment]
This has been fixed
