### ISSUE TITLE
set id_items=1 in act5, sometimes throw Exception after cain identify items

### ISSUE THREAD

**Issue by evilight** [aeon0/botty#741]
**Is it really a Bug report?**
yes

**Botty Version**
0.7.3-dev

**Describe the bug**
sometimes, when set id_items=1 in act5 , after id the items, bot will crash
[0.7.3-dev 2022-05-01 22:54:59,120] INFO       ID items at cain
[0.7.3-dev 2022-05-01 22:54:59,143] DEBUG      Traverse from a5_town_start to a5_qual_kehk
[0.7.3-dev 2022-05-01 22:55:30,193] ERROR      return_to_play(): failed to return to neutral play screen
[0.7.3-dev 2022-05-01 22:55:31,312] DEBUG      ['CLOSE_PANEL', 'CLOSE_PANEL_2'] not found after 1 seconds
[0.7.3-dev 2022-05-01 22:55:49,059] ERROR      return_to_play(): failed to return to neutral play screen

**To Reproduce**
1. set id_items=1
2. start the bot
3. sometimes, after close cain panel, the "save and exit" panel will show up, and disapear and then show up again, in the end, the bot will crash

**Expected behavior**
after indentify items from Cain, if bot send esc that should close Cain's panel but open "save and exit" panel instead, bot should detect that , just esc again and check if if return to play screen

**Screenshots / Video**
no

**Logs**
[0.7.3-dev 2022-05-01 22:54:59,120] INFO       ID items at cain
[0.7.3-dev 2022-05-01 22:54:59,143] DEBUG      Traverse from a5_town_start to a5_qual_kehk
[0.7.3-dev 2022-05-01 22:55:30,193] ERROR      return_to_play(): failed to return to neutral play screen
[0.7.3-dev 2022-05-01 22:55:31,312] DEBUG      ['CLOSE_PANEL', 'CLOSE_PANEL_2'] not found after 1 seconds
[0.7.3-dev 2022-05-01 22:55:49,059] ERROR      return_to_play(): failed to return to neutral play screen
Exception in thread Thread-11:
Traceback (most recent call last):
  File "D:\ProgramData\Miniconda\envs\botty\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "D:\ProgramData\Miniconda\envs\botty\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "Z:\github\D2R\botty\src\bot.py", line 156, in start
    self.trigger_or_stop('init')
  File "Z:\github\D2R\botty\src\bot.py", line 176, in trigger_or_stop
    self.trigger(name, **kwargs)
  File "D:\ProgramData\Miniconda\envs\botty\lib\site-packages\transitions\core.py", line 899, in _get_trigger
    return event.trigger(model, *args, **kwargs)
  File "D:\ProgramData\Miniconda\envs\botty\lib\site-packages\transitions\core.py", line 401, in trigger
    return self.machine._process(func)
  File "D:\ProgramData\Miniconda\envs\botty\lib\site-packages\transitions\core.py", line 1201, in _process
    self._transition_queue[0]()
  File "D:\ProgramData\Miniconda\envs\botty\lib\site-packages\transitions\core.py", line 426, in _trigger
    return self._process(event_data)
  File "D:\ProgramData\Miniconda\envs\botty\lib\site-packages\transitions\core.py", line 435, in _process
    if trans.execute(event_data):
  File "D:\ProgramData\Miniconda\envs\botty\lib\site-packages\transitions\core.py", line 272, in execute
    event_data.machine.callbacks(itertools.chain(event_data.machine.before_state_change, self.before), event_data)
  File "D:\ProgramData\Miniconda\envs\botty\lib\site-packages\transitions\core.py", line 1123, in callbacks
    self.callback(func, event_data)
  File "D:\ProgramData\Miniconda\envs\botty\lib\site-packages\transitions\core.py", line 1144, in callback
    func(*event_data.args, **event_data.kwargs)
  File "Z:\github\D2R\botty\src\bot.py", line 315, in on_maintenance
    items = personal.inspect_items(game_stats=self._game_stats)
  File "Z:\github\D2R\botty\src\inventory\personal.py", line 284, in inspect_items
    slot_pos, slot_img = common.get_slot_pos_and_img(img, column, row)
  File "Z:\github\D2R\botty\src\inventory\common.py", line 37, in get_slot_pos_and_img
    slot_img = img[min_y:max_y, min_x:max_x]
TypeError: 'NoneType' object is not subscriptable

**Additional info**
Add any other information about the problem here.

**Comment by mgleed** [comment]
This is a known issue. Workaround is having a tome of identify in inventory so it won't make you use Cain.
