### ISSUE TITLE
PLEASE HELP ME

### ISSUE THREAD

**Issue by WHYWEFAIL** [aeon0/botty#759]
failed to r[0.7.3 2022-05-10 11:58:40,610] DEBUG      Using WinAPI to search for window: WindowSpec(title_regex=None, process_name_regex='D2R\\.exe')
[0.7.3 2022-05-10 11:58:40,651] DEBUG      Set offsets: left 640px, top 340px
[0.7.3 2022-05-10 11:58:40,652] WARNING    Your D2R settings differ from the requiered ones. Please use Auto Settings to adjust them. The differences are:
[0.7.3 2022-05-10 11:58:40,681] WARNING    {'Gamma': [201, 155], 'GammaHD': [3200, 3024], 'Sharpening': [21, 6], 'Blended Shadows': [1, 0], 'Perspective': [1, 0], 'Framerate Cap': [70, 60], 'Framerate Target': [70, 0], 'Ambient Occlusion Quality': [1, 0], 'Atmospherics Quality': [4, 2], 'Anti Aliasing': [1, 0], 'Dynamic Resolution Scaling': [1, 0], 'Chat Font Size': [2, 0], 'Combat Feedback': [1, 0], 'Camera Shake': [1, 0], 'Low Vision Mode': [0, 1], 'Auto Gold Enabled': [1, 0], 'Quick Cast Enabled': [1, 0], 'Display Active Skill Bindings': [1, 0]}
Set D2R to be always on top
[0.7.3 2022-05-10 11:58:40,742] INFO       Start health monitoring
[0.7.3 2022-05-10 11:58:40,742] INFO       Start Death monitoring
[0.7.3 2022-05-10 11:58:41,033] INFO       Setting up Blizz Sorc
[0.7.3 2022-05-10 11:58:41,034] INFO       Doing runs: odict_keys(['run_pindle'])
[0.7.3 2022-05-10 11:58:41,037] INFO       Starting game #1
[0.7.3 2022-05-10 11:58:41,037] DEBUG      Waiting for templates: ['MAIN_MENU_TOP_LEFT', 'MAIN_MENU_TOP_LEFT_DARK', 'A5_TOWN_0', 'A5_TOWN_1', 'A4_TOWN_4', 'A4_TOWN_5', 'A3_TOWN_0', 'A3_TOWN_1', 'A2_TOWN_0', 'A2_TOWN_1', 'A2_TOWN_10', 'A1_TOWN_1', 'A1_TOWN_3']
[0.7.3 2022-05-10 11:58:42,998] DEBUG      Found Match: MAIN_MENU_TOP_LEFT (94.4% confidence)
[0.7.3 2022-05-10 11:58:43,025] DEBUG      Wait for Play button
[0.7.3 2022-05-10 11:58:43,042] DEBUG      Found Play Btn, select and press key: h
[0.7.3 2022-05-10 11:58:54,166] DEBUG      Found loading screen / creating game
[0.7.3 2022-05-10 11:58:54,442] DEBUG      Waiting for templates: ['A5_TOWN_0', 'A5_TOWN_1', 'A4_TOWN_4', 'A4_TOWN_5', 'A3_TOWN_0', 'A3_TOWN_1', 'A2_TOWN_0', 'A2_TOWN_1', 'A2_TOWN_10', 'A1_TOWN_1', 'A1_TOWN_3']
[0.7.3 2022-05-10 11:59:09,447] DEBUG      Found Match: A5_TOWN_1 (91.3% confidence)
[0.7.3 2022-05-10 11:59:10,099] INFO       Capabilities: CharacterCapabilities(can_teleport_natively=False, can_teleport_with_charges=True)
[0.7.3 2022-05-10 11:59:13,617] DEBUG      ['ITEM_PICKUP_ENABLED', 'ITEM_PICKUP_DISABLED'] not found after 1.3 seconds
[0.7.3 2022-05-10 11:59:13,618] ERROR      Failed to detect if /nopickup command was applied or not
[0.7.3 2022-05-10 11:59:14,343] ERROR      EXP OCR Error: ['I', '1', '12', '46']
[0.7.3 2022-05-10 11:59:14,344] ERROR      EXP OCR Error: 'EXPERIENCE:' is not in list
[0.7.3 2022-05-10 11:59:15,983] DEBUG      ['CLOSE_PANEL', 'CLOSE_PANEL_2'] not found after 1 seconds
[0.7.3 2022-05-10 11:59:24,661] ERROR      return_to_play(): failed to return to neutral play screen
[0.7.3 2022-05-10 11:59:26,148] DEBUG      ['CLOSE_PANEL', 'CLOSE_PANEL_2'] not found after 1 seconds
[0.7.3 2022-05-10 11:59:34,835] ERROR      return_to_play(): failed to return to neutral play screen
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "bot.py", line 156, in start
  File "bot.py", line 176, in trigger_or_stop
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 295, in on_maintenance
  File "inventory\consumables.py", line 109, in update_tome_key_needs
  File "template_finder.py", line 96, in search
TypeError: 'NoneType' object is not subscriptableeturn to neutral play screen

**Comment by derek337** [comment]
`WARNING Your D2R settings differ from the requiered ones. Please use Auto Settings to adjust them. The differences are:`

idk maybe try using the right settings?

**Comment by jagarop** [comment]
not a bug
