### ISSUE TITLE
Bot stops after chicken

### ISSUE THREAD

**Issue by RJL87** [aeon0/botty#773]
Im using the pre-compiled ver 0.7.3

After chicken the bot stops.

```
[0.7.3 2022-05-15 19:49:20,803] WARNING    Trying to chicken, merc HP 0.0%!
[0.7.3 2022-05-15 19:49:21,554] INFO       Health Manager is now pausing
Exception in thread Thread-6:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "game_controller.py", line 56, in run_bot
  File "game_stats.py", line 75, in log_chicken
  File "messages\messenger.py", line 25, in send_chicken
AttributeError: 'NoneType' object has no attribute 'send_chicken'
```

Thanks in advance.

**Comment by g00se01101** [comment]
Found a fix: 
Update param.ini
set message_api_type=generic_api;

**Comment by D2RLegit** [comment]
Issue resolved.
