### ISSUE TITLE
Failed to detect if /nopickup command was a pplied or not

### ISSUE THREAD

**Issue by hutber** [aeon0/botty#774]
I have Python 2.7 installed, though as the package is running from the latest built version I am not sure this is relevant.

I downloaded https://github.com/aeon0/botty/releases/download/v0.7.3/botty_v.0.7.3.rar extracted it and then ran it, everything works as expected until I hit f11 to get the bot to start. It is installed in `C:\Program Files (x86)\Diablo II Resurrected\botty_v0.7.3` 

I start the bot while in the lobby and nothing happens, so I created a game and then started the bot. It starts, it sets `/notpickit` but does not get a confirmation back in the bot as seen below.

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "psutil\_common.py", line 441, in wrapper
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "screen.py", line 37, in detect_window_position
  File "screen.py", line 41, in find_and_set_window_position
  File "utils\misc.py", line 54, in find_d2r_window
  File "utils\misc.py", line 43, in match
  File "psutil\__init__.py", line 624, in name
  File "psutil\_pswindows.py", line 759, in name
  File "psutil\_pswindows.py", line 690, in wrapper
  File "psutil\_pswindows.py", line 680, in convert_oserror
  File "psutil\_pswindows.py", line 688, in wrapper
  File "psutil\_common.py", line 444, in wrapper
  File "psutil\_pswindows.py", line 775, in exe
OSError: [WinError 87] Invalid parameter: '(originated from NtQuerySystemInforma
tion)'
Set D2R to be always on top
[0.7.3 2022-05-15 23:31:20,921] INFO       Start health monitoring
[0.7.3 2022-05-15 23:31:20,922] INFO       Start Death monitoring
[0.7.3 2022-05-15 23:31:21,043] INFO       Setting up Light Sorc
[0.7.3 2022-05-15 23:31:21,044] INFO       Doing runs: odict_keys(['run_pindle',
 'run_shenk'])
[0.7.3 2022-05-15 23:31:21,045] INFO       Starting game #1
[0.7.3 2022-05-15 23:31:21,046] DEBUG      Waiting for templates: ['MAIN_MENU_TO
P_LEFT', 'MAIN_MENU_TOP_LEFT_DARK', 'A5_TOWN_0', 'A5_TOWN_1', 'A4_TOWN_4', 'A4_T
OWN_5', 'A3_TOWN_0', 'A3_TOWN_1', 'A2_TOWN_0', 'A2_TOWN_1', 'A2_TOWN_10', 'A1_TO
WN_1', 'A1_TOWN_3']
[0.7.3 2022-05-15 23:31:28,500] DEBUG      Found Match: A5_TOWN_1 (72.7% confide
nce)
[0.7.3 2022-05-15 23:31:28,502] DEBUG      Waiting for templates: ['A5_TOWN_0',
'A5_TOWN_1', 'A4_TOWN_4', 'A4_TOWN_5', 'A3_TOWN_0', 'A3_TOWN_1', 'A2_TOWN_0', 'A
2_TOWN_1', 'A2_TOWN_10', 'A1_TOWN_1', 'A1_TOWN_3']
[0.7.3 2022-05-15 23:31:34,768] DEBUG      Found Match: A5_TOWN_1 (72.7% confide
nce)
[0.7.3 2022-05-15 23:31:34,970] INFO       Capabilities: CharacterCapabilities(c
an_teleport_natively=False, can_teleport_with_charges=False)
[0.7.3 2022-05-15 23:31:38,589] DEBUG      ['ITEM_PICKUP_ENABLED', 'ITEM_PICKUP_
DISABLED'] not found after 1.3 seconds
[0.7.3 2022-05-15 23:31:38,590] ERROR      Failed to detect if /nopickup command
 was applied or not
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 973, in _bootstrap_inner
  File "threading.py", line 910, in run
  File "bot.py", line 156, in start
  File "bot.py", line 176, in trigger_or_stop
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 268, in on_start_from_town
  File "game_stats.py", line 111, in log_exp
  File "ui\player_bar.py", line 12, in get_experience
  File "screen.py", line 89, in convert_screen_to_monitor
TypeError: Value after * must be an iterable, not NoneType

```

**Comment by namdnas23** [comment]
Have you hit F9 to set the brightness and other settings applied by the bot upon initial setup? I have found that it will not register things properly until you do this.

**Comment by hutber** [comment]
Thanks @namdnas23  ye, I just doubled checked myself too. f9 works successfully and reports back 
```
Process "D2R.exe" with PID 1180 was forcibly terminated.
Adapted settings succesfully. You can now restart D2R.
```
Then, with the screen open and the correct character selected:
![image](https://user-images.githubusercontent.com/1344898/168817605-7e3f827a-ca91-4733-967f-ddba0fbb97b5.png)

**Comment by namdnas23** [comment]
@hutber Hmmm have you tried reinstalling from scratch. Maybe save your configs unless you can just retype all the changes you have done and try again. Maybe just fresh install in a new directory and make sure you didn't make a breaking change somewhere?

**Comment by hutber** [comment]
Good suggestion indeed @namdnas23. It sadly didn't fix things.
I am wondering if somehow a dependency is missing from my windows installation? Something net framework or possibly python? I'm running an extremely barebones version of windows!

**Comment by D2RLegit** [comment]
I would assume you have your top corners are blocked by something.

**Comment by hutber** [comment]
Interesting, its all done by position on the monitor. I shall try debug mode now!

**Comment by hutber** [comment]
So I believe you are right, this is the debug image, it cannot find the d2r window? 
![image](https://user-images.githubusercontent.com/1344898/168930308-8b0d20c3-9828-43f6-8899-7c6a83836125.png)

**Comment by D2RLegit** [comment]
Its something to do with the extra monitors, but idk how to fix. I'm sure someone on the discord has the answer. I don't have dual monitors to troubleshoot.

**Comment by hutber** [comment]
I guess it must be as its running in Wine that it cannot understand the monitor setup. I wonder if there is a way to tell it what my screens are and how they are setup :/
![Screenshot from 2022-05-23 20-02-11](https://user-images.githubusercontent.com/1344898/169888523-8a4c12c2-2cbf-4742-a271-baba90c202df.png)

**Comment by hutber** [comment]
![Screenshot from 2022-05-23 20-02-50](https://user-images.githubusercontent.com/1344898/169888593-d2333338-a6ca-40ca-a721-29ce4789037d.png)

**Comment by hutber** [comment]
It says my wine is windows 10 for confirmation. Sorry for the delay, using version 0.8.0 now to test this.
![image](https://user-images.githubusercontent.com/1344898/174331950-ac41b379-3f53-4fbc-a864-5595bd551d87.png)
