### ISSUE TITLE
If you go around Chaos Saint-Turrier with Sorceress, center hole and stop

### ISSUE THREAD

**Issue by anoldan** [aeon0/botty#797]
**Is it really a Bug report?**
If you have questions regarding setup or feature information/requests, please consider asking in the Discord channel: https://discord.gg/Jf3J8cuXWg. The Github issues section is for bug reports only.

If you go around Chaos Saint-Turrier with Sorceress, teleport it three times in the 11 o'clock direction from the center hole and stop.

**Botty Version**
What version of botty are you running? Are you using a pre-compiled release? Which one. Are you using the latest master branch? On which commit?

**Describe the bug**

**To Reproduce**
3. etc.

**Expected behavior**

**Screenshots / Video**
If applicable, add screenshots or even better a short video of the error happening to help explain your problem. Botty often automatically makes screenshots when something goes wrong. Add these also.

**Logs**
Add the relevant part of the info.log in this section. Either upload it as a fail or copy-paste the relevant part in here.

**Additional info**
Add any other information about the problem here.

**Comment by anoldan** [comment]
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\KING\miniconda3\envs\botty\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\KING\miniconda3\envs\botty\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\KING\Downloads\botty-master\botty-master\src\bot.py", line 161, in start
    self.trigger_or_stop('init')
  File "C:\Users\KING\Downloads\botty-master\botty-master\src\bot.py", line 181, in trigger_or_stop
    self.trigger(name, **kwargs)
  File "C:\Users\KING\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 899, in _get_trigger
    return event.trigger(model, *args, **kwargs)
  File "C:\Users\KING\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 401, in trigger
    return self.machine._process(func)
  File "C:\Users\KING\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1201, in _process
    self._transition_queue[0]()
  File "C:\Users\KING\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 426, in _trigger
    return self._process(event_data)
  File "C:\Users\KING\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 435, in _process
    if trans.execute(event_data):
  File "C:\Users\KING\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 272, in execute
    event_data.machine.callbacks(itertools.chain(event_data.machine.before_state_change, self.before), event_data)
  File "C:\Users\KING\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1123, in callbacks
    self.callback(func, event_data)
  File "C:\Users\KING\miniconda3\envs\botty\lib\site-packages\transitions\core.py", line 1144, in callback
    func(*event_data.args, **event_data.kwargs)
  File "C:\Users\KING\Downloads\botty-master\botty-master\src\bot.py", line 530, in on_run_diablo
    res = self._diablo.battle(not self._pre_buffed)
  File "C:\Users\KING\Downloads\botty-master\botty-master\src\run\diablo.py", line 475, in battle
    if not self._layoutcheck("A", "Vizier", "dia_a_layout", "layoutcheck_a", [610620], 0.81 , None, ["DIA_A2Y_LAYOUTCHECK0", "DIA_A2Y_LAYOUTCHECK1", "DIA_A2Y_LAYOUTCHECK2", "DIA_A2Y_LAYOUTCHECK4", "DIA_A2Y_LAYOUTCHECK5", "DIA_A2Y_LAYOUTCHECK6"], ["DIA_A1L_LAYOUTCHECK0", "DIA_A1L_LAYOUTCHECK4", "DIA_A1L_LAYOUTCHECK4LEFT", "DIA_A1L_LAYOUTCHECK1", "DIA_A1L_LAYOUTCHECK2", "DIA_A1L_LAYOUTCHECK3","DIA_A1L_LAYOUTCHECK4RIGHT","DIA_A1L_LAYOUTCHECK5"]): return False
  File "C:\Users\KING\Downloads\botty-master\botty-master\src\run\diablo.py", line 367, in _layoutcheck
    self._char.kill_cs_trash(trash_location)
  File "C:\Users\KING\Downloads\botty-master\botty-master\src\char\i_char.py", line 349, in kill_cs_trash
    raise ValueError("Diablo CS Trash is not implemented!")

**Comment by D2RLegit** [comment]
Only works for hammerdin.

**Comment by Greenapple2021** [comment]
work with all of classes only need to be edited
